#!/data/data/com.termux/files/usr/bin/bash

pkg up -y;
echo "install dependencies";
pkg i unstable-repo -y;
pkg i termux-api -y;
pkg i runit termux-services -y;
termux-setup-storage;
sleep 30;
pkg i php apache2 php-apache -y;
pkg i mariadb composer -y;
cp php.conf $PREFIX/etc/apache2/conf.d/php.conf;
rm $PREFIX/etc/apache2/httpd.conf;
cp httpd.conf $PREFIX/etc/apache2/httpd.conf;
echo "success replace config php.conf & httpd.conf";
mkdir /sdcard/htdocs;
echo "success make dir /sdcard/htdocs";
cp index.html /sdcard/htdocs;
ln -s /sdcard/htdocs ~/htdocs;
echo "success linking /sdcard/htdocs/ to ~/htdocs";
composer create-project --working-dir=/sdcard/htdocs phpmyadmin/phpmyadmin;
composer update --working-dir=/sdcard/htdocs/phpmyadmin;
echo "success install phpmyadmin with composer";
composer create-project --working-dir=/sdcard/htdocs codeigniter4/appstarter ci4 --no-dev;
composer update --working-dir=/sdcard/htdocs/ci4;
echo "success install codeigniter 4 with composer";
composer require --working-dir=/sdcard/htdocs/ci4 myth/auth;
echo "success install apache mariadb php phpmyadmin and codeigniter4 with myth/auth";
cp run-httpd-mysqld.sh ~/run-httpd-mysqld.sh;
cp stop-httpd-mysqld.sh ~/stop-httpd-mysqld.sh;
cp config.inc.php /sdcard/htdocs/phpmyadmin;

echo "success copy paste script run and stop httpd mysqld";
echo "now, you have to configure mysql by typing manually this script";
echo "";
echo "CREATE USER 'root' IDENTIFIED BY '';";
echo "GRANT ALL ON db.* TO root@localhost IDENTIFIED BY '';";
echo "FLUSH PRIVILEGES;";
echo "quit;";
echo "";
echo "";
sv-enable httpd;
sv-enable mysqld;
mariadb;
